/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook-14.glb -T
Files: macbook-14.glb [629.72KB] > /Users/adrianhajdin/Desktop/macbook_gsap_app/public/models/macbook-14-transformed.glb [627.9KB] (0%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import {useEffect} from 'react'
import {useGLTF, useTexture} from '@react-three/drei'
import useMacbookStore from "../../store";
import {noChangeParts} from "../../constants/index.js";
import {Color, SRGBColorSpace, Mesh, Material} from 'three'
import type { ThreeElements } from '@react-three/fiber';

type MacbookModel14Props = ThreeElements['group'] & {
    scale?: number;
}

export default function MacbookModel14(props: MacbookModel14Props) {
    const { color } = useMacbookStore();
  const { nodes, materials, scene } = useGLTF('/models/macbook-14-transformed.glb');

  const texture = useTexture('/screen.png');
    texture.colorSpace = SRGBColorSpace;
    texture.needsUpdate = true;

  useEffect(() => {
    scene.traverse((child) => {
        if(child.type === 'Mesh') {
            const mesh = child as Mesh;
            if(!noChangeParts.includes(child.name) && mesh.material) {
                const material = mesh.material as Material;
                (material as any).color = new Color(color);
            }
        }
    })
  }, [color, scene])

  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes as any).Object_10.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_16.geometry} material={materials.zhGRTuGrQoJflBD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_20.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_22.geometry} material={materials.lmWQsEjxpsebDlK} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_30.geometry} material={materials.LtEafgAVRolQqRw} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_32.geometry} material={materials.iyDJFXmHelnMTbD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_34.geometry} material={materials.eJObPwhgFzvfaoZ} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_38.geometry} material={materials.nDsMUuDKliqGFdU} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_42.geometry} material={materials.CRQixVLpahJzhJc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_48.geometry} material={materials.YYwBgwvcyZVOOAA} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_54.geometry} material={materials.SLGkCohDDelqXBu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_58.geometry} material={materials.WnHKXHhScfUbJQi} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_66.geometry} material={materials.fNHiBfcxHUJCahl} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_74.geometry} material={materials.LpqXZqhaGCeSzdu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_82.geometry} material={materials.gMtYExgrEUqPfln} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_96.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_107.geometry} material={materials.JvMFZolVCdpPqjj} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes as any).Object_123.geometry} rotation={[Math.PI / 2, 0, 0]} >
          <meshBasicMaterial map={texture} />
      </mesh>
      <mesh geometry={(nodes as any).Object_127.geometry} material={materials.ZCDwChwkbBfITSW} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/macbook-14-transformed.glb')